//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagerverwaltungLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public int LagerortId { get; set; }
        public string Materialnummer { get; set; }
        public string Materialbezeichnung { get; set; }
        public double Standardpreis { get; set; }
        public int Bestand { get; set; }
        public int Mindestbestand { get; set; }
        public int Bestellmenge { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        public virtual Lagerort Lagerort { get; set; }
    }
}
